# Generated by Django 4.2.3 on 2023-07-20 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
